### ISSUE TITLE
Requesting input for CI

### ISSUE THREAD

**Issue by cboulay** [xdf-modules/xdf-Python#12]
We need to setup CI for this repo. It seems like there have been some changes in the CI landscape recently. Any recommendations?

For now the project is pure Python so we really only need a Linux host, but this might not always be true.

**Comment by tstenner** [comment]
Travis once was an option, but the slow adoption of Ubuntu 16(!).04 and the buyout last year make me hesistant to try them again.

I quite like Appveyor and I could recommend them without hesitation.

Some Python projects use CircleCI, but I haven't worked with it.

Azure pipelines has all major platforms (in case we want to create binary modules), but the build configuration is more involved than with Appveyor.

**Comment by cbrnr** [comment]
I'm currently setting up Azure Pipelines for MNELAB because they have Linux, macOS, and Windows. MNE has a working config, and mine also works, so I can help setting that up.

**Comment by cboulay** [comment]
I've setup Azure Pipelines.

* PRs and pushes to master should trigger build and running the test suite (so far one dummy test).
* Pushing a tag should trigger a build, test, and deploy to pypi. The version comes from the tag, and there are some rules around versioning. Try using this format: `git tag -a v1.15.1b3 -m 'cool feature'`
