### ISSUE TITLE
New release on PyPI (1.15)

### ISSUE THREAD

**Issue by cbrnr** [xdf-modules/xdf-Python#14]
@cboulay I think we should make a new release on PyPI because we fixed some important bugs. Do you have time to upload the new release? You might want to consider merging #10, #11, and #13 before that.

**Comment by cboulay** [comment]
I've looked them over briefly and they all seem fine. However, I haven't tested at all.
IMO if you and Tristan both agree that it should be merged then I don't need to be in the conversation.

Do you have the ability to merge them? I thought your status on the xdf-modules group would give you credentials for all of its sub-repos. If not then let me know and I'll add you here too.

**Comment by cbrnr** [comment]
Yes, I have permissions to merge, but I thought you wanted to have a final look. I have tested only briefly myself and all changes seem to be fine. If you don't have time to look more closely I'll go ahead and merge. Can you make the new release then?

**Comment by cboulay** [comment]
Yes I'll do the release if you merge. I'd like to setup CI for this repo so a release is automatic when there's a tagged commit in master, but I won't have time to do that this week.

**Comment by cbrnr** [comment]
We're good to go.

**Comment by cboulay** [comment]
Ok I’m occupied for a little while. I will try to get to this tonight.

**Comment by cboulay** [comment]
https://pypi.org/project/pyxdf/1.15.1/
