### ISSUE TITLE
Create what's new

### ISSUE THREAD

**Issue by cbrnr** [xdf-modules/xdf-Python#15]
We should document all changes in a what's new file. I suggest that we create a Markdown file in the project root, but I'm not sure if there's a best practice regarding file name or format.

**Comment by cboulay** [comment]
A couple things to try:

https://github.com/github-changelog-generator/github-changelog-generator
https://github.com/github-tools/github-release-notes

**Comment by cbrnr** [comment]
OK, so let's call the file `CHANGELOG.md`. I suggest that we edit it manually for now, because I don't expect that we will have dozens of changes in each release. We should use the format described in this guide: https://keepachangelog.com/en/1.0.0/

**Comment by cboulay** [comment]
Can you make the first one? I'm a bit burnt out on maintenance at the moment (not only xdf but a couple other projects I work on).
