### ISSUE TITLE
Import version from pyxdf.py

### ISSUE THREAD

**Issue by cbrnr** [xdf-modules/xdf-Python#16]
In setup.py, we should not define the version number again, because we already do that in pyxdf.py.

**Comment by cboulay** [comment]
It needs to be in setup.py for pypi. Maybe we can get setup.py to read it from another file. Do you have any good examples of that?

**Comment by cboulay** [comment]
[setuptools-scm](https://pypi.org/project/setuptools-scm/) looks interesting. Maybe I'll give that a try.

**Comment by cboulay** [comment]
Fixed in 28d79d4921e2c6a204e6c94117d10c18c491b9a6

**Comment by cbrnr** [comment]
Nice solution!
