### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by cbrnr** [xdf-modules/xdf-Python#25]
The main module `pyxdf.py` currently contains the following copyright statement at the top of the file:
```
Copyright (c) 2015-2018, Syntrogi Inc. dba Intheon
```

The docstring of `load_xdf` contains another copyright notice:
```
    License:
        This file is covered by the BSD license.

        Copyright (c) 2015-2018, Syntrogi Inc. dba Intheon

        Redistribution and use in source and binary forms, with or without
        modification, are permitted provided that the following conditions are
        met:

            * Redistributions of source code must retain the above copyright
              notice, this list of conditions and the following disclaimer.
            * Redistributions in binary form must reproduce the above copyright
              notice, this list of conditions and the following disclaimer in
              the documentation and/or other materials provided with the
              distribution

        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
        "AS IS AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
        LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
        A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
        OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
        SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
        LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
        DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
        THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (
        INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
        OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

How do we proceed? First, we need to update the year to 2019. Second, I am starting to change more in the code so it would be nice if this was acknowledged somewhere. Third, I think we should put the current maintainers as copyright holders (but of course continue to mention Syntrogi Inc. dba Intheon). Here's a suggestion of what I'd put at the top of the file:
```
Authors: Syntrogi Inc. dba Intheon
         Clemens Brunner <mail address>
         Tristan Stenner <mail address>
         Chadwick Boulay <mail address>
         <others?>

License: BSD (2-clause)
```
Then I'd remove the copyright and license notice from the function docstring completely.

It would be even nicer if we could add the names of the original authors instead of/in addition to Syntrogi (@chkothe?).

Thoughts @cboulay @tstenner?

**Comment by tstenner** [comment]
Fine by me, but I don't know much about the copyright situation except that in most cases Christian was ok with a plain BSD license. @cboulay should know more about that.

**Comment by cbrnr** [comment]
I forgot that we already have the whole project licensed under the BSD 2-clause license (we have `LICENSE` in our root folder). So I guess I'll go ahead and submit a PR with the proposed changes.

**Comment by cboulay** [comment]
We can close this and move discussion to #26.
