### ISSUE TITLE
Release 1.15.2

### ISSUE THREAD

**Issue by cbrnr** [xdf-modules/xdf-Python#27]
I really need #19, which has already been merged, for MNELAB. @cboulay could you please upload a new release (1.15.2) to PyPI (please modify `CHANGELOG.md` first by adding the release date)? If you don't have time, I can also do it, just let me know (do I have proper permissions to upload to PyPI?).

**Comment by cboulay** [comment]
I think you can do it. All you have to do it make a tagged release and it should auto-upload to pypi.

**Comment by cbrnr** [comment]
Nice, that was easy! Thanks!
