### ISSUE TITLE
Rename xdf-Python to xdf-python

### ISSUE THREAD

**Issue by cbrnr** [xdf-modules/xdf-python#32]
I know this is a tiny nitpick, but could we rename this repository to xdf-python (with a small p)? It kind of hurts my eyes everytime I look at it (which is admittedly a very subjective argument), and not mixing upper and lower case in names also causes fewer problems (e.g. on non-case-sensitive file systems that are still used e.g. on macOS by default).

**Comment by tstenner** [comment]
Looks good to me. IIRC Github will automatically redirect the old URL to the new one when moving the repository, but I don't know if it also does it when renaming it. Still, better now than later.

**Comment by cbrnr** [comment]
In this case it doesn't even matter, because https://github.com/xdf-modules/xdf-python is already working (URLs are generally not case-sensitive).

**Comment by agricolab** [comment]
i second it, good idea to change to lower-case.

**Comment by cbrnr** [comment]
Alright, then I'll make the change. @cboulay @tstenner @agricolab you might want to change xdf-Matlab as well.
