### ISSUE TITLE
Release 0.16.0

### ISSUE THREAD

**Issue by cbrnr** [xdf-modules/xdf-python#40]
I think it's time for a new release. We have a new feature (reading only specific streams) and important fixes. I can do the release, but let me know if there's something stopping us. @cboulay @tstenner

**Comment by cboulay** [comment]
I’d like to re add the ‘verbose’ argument. 

Internet is temporarily down chez moi and I should go to bed. I can elaborate tomorrow.

**Comment by cboulay** [comment]
Let's get #41 sorted before we make a new release.

**Comment by cbrnr** [comment]
Are we ready for the release? @cboulay do you want to do it or should I?

**Comment by cboulay** [comment]
Please go ahead. Btw, I don’t think you need to do a pr for change log edits.
