### ISSUE TITLE
Re-add verbose argument to `load_xdf`

### ISSUE THREAD

**Issue by cboulay** [xdf-modules/xdf-python#41]
The short of it is that I updated some Intheon code to no longer use 'verbose' in the call to `load_xdf`. Then @chkothe reverted that changed and pinned their use of pyxdf to an older version. So obviously this is important to them though I haven't had a conversation as to why.

Looking back, it seems that I'm the one that removed it [in this commit](https://github.com/sccn/xdf/commit/0428fe0aaa5f8565141342c98b3610e6f9d5ed55#diff-8dbbae27ec1074622bb151a61e0fb80e). The only thing related I see is [this comment](https://github.com/sccn/xdf/pull/6#issuecomment-263812175). So I guess my interpretation was "why use a 'verbose' argument when you should be setting the logger level separately?".

So if we re-add the verbose argument, does that mean we should use it to override the logger level? Or if verbose is set, do we skip the logger output and print to screen?

**Comment by chkothe** [comment]
I think the strongest argument is probably to not break backwards compatibility (even though pyxdf is relatively new). But other than that, and acknowledging that the verbose flag was probably carried over from some MATLAB code, it's more convenient to pass a bool into a verbose flag than to work out and manicure some configurable per-module logging setup, and pass the bool into that. 

I think this package is mostly useful for data scientists and neuroscientists, who I think appreciate a quick solution that gets the job done without much software engineering -- or to not necessarily technical end users of larger packages in the style of EEGLAB or MNE, where a lot of the details and responsible modules are sometimes obscure to them, but one can at least hope that all the options of the underlying import functions are exposed somehow by that kind of software.

Unfortunately there's only a single "debug" log level in Python, and pyxdf is rather spammy at that level, making application-wide debug logs pretty hard to traverse out of the box without such a facility in place.

**Comment by cboulay** [comment]
Are you advocating for not using the logger at all? Or only when verbose=True?

**Comment by chkothe** [comment]
IIRC it was just suppressing some of logger messages when set to False (probably all, but that's maybe a bit too much). We could make it suppress just the detailed per-chunk messages if False.

**Comment by cboulay** [comment]
Can we default to verbose=True? People who rely on logger entirely might want to ignore the verbose argument yet still get the debug statements (because that's how they configured their logger). If so then the `verbose` argument would effectively be equivalent to `allow_debug_logging`, though we won't name it that.

[Relevant link for logging levels](https://docs.python.org/3/library/logging.html#levels)

**Comment by chkothe** [comment]
I think that would make sense.
