### ISSUE TITLE
Version 1.16.0 does not work with Python 2.7 anymore

### ISSUE THREAD

**Issue by hoechenberger** [xdf-modules/xdf-python#44]
```python
$ python -V
Python 2.7.15
$ python -c 'import pyxdf'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/hoechenberger/miniconda3/envs/pyxdf/lib/python2.7/site-packages/pyxdf/__init__.py", line 11, in <module>
    from .pyxdf import load_xdf, resolve_streams, match_streaminfos
  File "/Users/hoechenberger/miniconda3/envs/pyxdf/lib/python2.7/site-packages/pyxdf/pyxdf.py", line 746
    chunk = {**chunk, **_parse_streamheader(xml)}
              ^
SyntaxError: invalid syntax
```

Metadata in `setup.py` says it should be compatible with both Py2 and Py3:
https://github.com/xdf-modules/xdf-python/blob/049aef3486040851f53ca710cee761c796b6835f/setup.py#L63-L64

**Comment by cbrnr** [comment]
OK, we should remove Python 2 in the metadata then.

**Comment by cboulay** [comment]
I know Python 2 is EOL and we really shouldn't be putting any resources into supporting it. That being said, I know some scientific equipment runs only on really old computers and works only with really old software that can't be updated, so some users might not have a choice. If anyone can present a compelling argument to include Python 2 support then maybe we can figure out how to do that.

**Comment by hoechenberger** [comment]
Just for the record, I personally couldn't care less about Py2. Just incidentally figured that Py2 wasn't working anymore as an automated build of the pyxdf conda-forge package failed.

**Comment by tstenner** [comment]
Right, that's why pylsl should drop it any time soon.

Reading the data back in isn't one of those infrastructure projects where some ancient program/library has to be kept. I don't have the stats, but I guess most of the postprocessing will run on conda so I'd argue Python 3.5 or whatever the second most recent Ubuntu LTS ships is old enough.

**Comment by cbrnr** [comment]
Even if someone really needs to load XDF files on an ancient platform (which I doubt because this is part of data analysis and not recording), they can still use the old 1.15 release.
